server:
  port: 8082
spring:
#  rabbitmq:
#    host: 39.108.254.46
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: /kf
#  transaction:
#    rollback-on-commit-failure: true
  application:
    name: redistest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
   database: 0
   host: 39.108.254.46
   port: 6379
   password:
   jedis:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
  timeout: 5000
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.hkf.demo.redistest.demo.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
